\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Reseach Questions},
            pdfauthor={Ulita Gilbert},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Fix footnotes in tables (requires footnote package)
\IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{longtable}}{}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{Reseach Questions}
\author{Ulita Gilbert}
\date{3 May 2021}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

In this part of my project I will refine my research questions. I will
further examine the effects of the pandemic on recent MCPS highschool
graduates enrolled at Montgomery College. For the purposes of this study
I will limit my dataset to MCPS students under the age of 20. These MCPS
students will be divided further into subgroups based on Gender and
Race. The datasets used in this part of my project have already been
cleaned in my initial data analysis.

\hypertarget{data-dictionary}{%
\section{Data Dictionary}\label{data-dictionary}}

For the purposes of this Project the following variables and definitions
are important.

\textbf{Terminology:}\\
\textbf{Fall2019} refers to the incoming freshman cohort in Fall2019.
This is term year 2020.\\
\textbf{Fall2020} refers to the incoming freshman cohort in Fall2020.
This is term year 2021.

\textbf{Variables of Interest:}\\
\textbf{term year:} incoming students in Fall 2019 are assigned to term
year 2020. Incoming students in Fall 2020 are assigned to term year
2021.\\
\textbf{hours\_earned:} refers to credit hours the student has earned in
their first Fall semester. This can include credits earned in Summer
school second session (Summer 2) and AP credits earned in high school.\\
\textbf{hours\_attempted:} refers to credit and non credit hours the
student has attempted in their first Fall semester. This may include
credits attempted in Summerschool second session - Summer 2.\\
\textbf{full\_part:} is the student full-time (FT) or part-time (PT).
This classification is based on the students self reported information
in the admissions application. Students are classified as full-time if
they intend to take at least 12 credits.\\
\textbf{major:} degree programme student is registered for or
certificate\&LR ( letter of recommendation.) All certificates and
letters of recommendations have been grouped together.\\
\textbf{hours\_earned\_rate:} Ratio of hours\_earned/hours\_attempted\\
\textbf{age:} age of student at the start of program.\\
\textbf{race:} racial classification of student. This is based on the
IPEDS system. Foreign students are identified as foreign and not by
their race/ethnicity.\\
\textbf{sex:} gender classification of student.\\
\textbf{high\_school:} name of highschool student graduted from. Public
High schools in Montgomery county are classified as MCPS.\\
\textbf{pell:} Whether the student received a pell grant or not.

\hypertarget{data-wrangling}{%
\section{Data Wrangling}\label{data-wrangling}}

\hypertarget{import-data}{%
\subsection{Import Data}\label{import-data}}

Summary of Data and Types

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{skim}\NormalTok{(df_Degrees)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule
\endhead
Name & df\_Degrees\tabularnewline
Number of rows & 7123\tabularnewline
Number of columns & 24\tabularnewline
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ &\tabularnewline
Column type frequency: &\tabularnewline
character & 15\tabularnewline
logical & 1\tabularnewline
numeric & 8\tabularnewline
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ &\tabularnewline
Group variables & None\tabularnewline
\bottomrule
\end{longtable}

\textbf{Variable type: character}

\begin{longtable}[]{@{}lrrrrrrr@{}}
\toprule
skim\_variable & n\_missing & complete\_rate & min & max & empty &
n\_unique & whitespace\tabularnewline
\midrule
\endhead
sex & 0 & 1.00 & 1 & 1 & 0 & 4 & 0\tabularnewline
race & 0 & 1.00 & 5 & 22 & 0 & 9 & 0\tabularnewline
age & 0 & 1.00 & 4 & 7 & 0 & 5 & 0\tabularnewline
high\_school & 0 & 1.00 & 7 & 30 & 0 & 163 & 0\tabularnewline
full\_part & 0 & 1.00 & 2 & 2 & 0 & 2 & 0\tabularnewline
city & 19 & 1.00 & 5 & 19 & 0 & 127 & 0\tabularnewline
stat\_code & 19 & 1.00 & 2 & 2 & 0 & 16 & 0\tabularnewline
pell\_grant & 0 & 1.00 & 1 & 1 & 0 & 2 & 0\tabularnewline
camp\_code & 140 & 0.98 & 1 & 1 & 0 & 6 & 0\tabularnewline
major & 0 & 1.00 & 1 & 61 & 0 & 34 & 0\tabularnewline
pass\_engl & 0 & 1.00 & 1 & 1 & 0 & 2 & 0\tabularnewline
pass\_math & 0 & 1.00 & 1 & 1 & 0 & 2 & 0\tabularnewline
summer1 & 0 & 1.00 & 1 & 1 & 0 & 1 & 0\tabularnewline
fall & 0 & 1.00 & 1 & 1 & 0 & 1 & 0\tabularnewline
HS\_classify & 0 & 1.00 & 2 & 14 & 0 & 7 & 0\tabularnewline
\bottomrule
\end{longtable}

\textbf{Variable type: logical}

\begin{longtable}[]{@{}lrrrl@{}}
\toprule
skim\_variable & n\_missing & complete\_rate & mean &
count\tabularnewline
\midrule
\endhead
MCPS & 0 & 1 & 0.7 & TRU: 4963, FAL: 2160\tabularnewline
\bottomrule
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}lrrrrrrrrrl@{}}
\toprule
\begin{minipage}[b]{0.10\columnwidth}\raggedright
skim\_variable\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\raggedleft
n\_missing\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
complete\_rate\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
mean\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\raggedleft
sd\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\raggedleft
p0\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
p25\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
p50\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\raggedleft
p75\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\raggedleft
p100\strut
\end{minipage} & \begin{minipage}[b]{0.03\columnwidth}\raggedright
hist\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.10\columnwidth}\raggedright
u\_number\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
20196625.60\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
5027.06\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
20190001\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
20191872.50\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
20193733.00\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
20201703.5\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
20203588.0\strut
\end{minipage} & \begin{minipage}[t]{0.03\columnwidth}\raggedright
▇▃▁▂▇\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\raggedright
zip\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
19\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
20886.64\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
1559.40\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
1460\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
20853.00\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
20877.00\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
20903.0\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
94025.0\strut
\end{minipage} & \begin{minipage}[t]{0.03\columnwidth}\raggedright
▁▇▁▁▁\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\raggedright
hours\_attempted\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
12.46\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
6.23\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
9.00\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
12.00\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
15.0\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
54.0\strut
\end{minipage} & \begin{minipage}[t]{0.03\columnwidth}\raggedright
▆▇▁▁▁\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\raggedright
hours\_earned\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
7.85\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
7.43\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
3.00\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
6.00\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
12.0\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
54.0\strut
\end{minipage} & \begin{minipage}[t]{0.03\columnwidth}\raggedright
▇▃▁▁▁\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\raggedright
mc\_gpa\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2.19\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
1.47\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0.67\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2.50\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
3.5\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
4.0\strut
\end{minipage} & \begin{minipage}[t]{0.03\columnwidth}\raggedright
▆▂▃▅▇\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\raggedright
term\_year\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2020.47\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.50\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
2020\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2020.00\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2020.00\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2021.0\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2021.0\strut
\end{minipage} & \begin{minipage}[t]{0.03\columnwidth}\raggedright
▇▁▁▁▇\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\raggedright
hours\_earned\_rate\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0.57\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0.38\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0.23\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0.64\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1.0\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
3.2\strut
\end{minipage} & \begin{minipage}[t]{0.03\columnwidth}\raggedright
▇▇▁▁▁\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.10\columnwidth}\raggedright
unearned\_hours\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
4.61\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
4.24\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
-22\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0.00\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
4.00\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
7.0\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
25.0\strut
\end{minipage} & \begin{minipage}[t]{0.03\columnwidth}\raggedright
▁▁▇▂▁\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

Change Datatypes

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_Degrees}\OperatorTok{$}\NormalTok{u_number<-}\StringTok{ }\KeywordTok{as.character}\NormalTok{(df_Degrees}\OperatorTok{$}\NormalTok{u_number)}
\NormalTok{df_Degrees}\OperatorTok{$}\NormalTok{term_year<-}\StringTok{ }\KeywordTok{as.character}\NormalTok{(df_Degrees}\OperatorTok{$}\NormalTok{term_year)}
\end{Highlighting}
\end{Shaded}

\hypertarget{create-dataframe-of-students-who-graduated-mcps-high-schools-who-are-20yrs-and-under-.}{%
\subsection{Create DataFrame of students who graduated MCPS high schools
who are 20yrs and under
.}\label{create-dataframe-of-students-who-graduated-mcps-high-schools-who-are-20yrs-and-under-.}}

Use the dataframe df\_Degrees which has been cleaned in the initial data
analysis. Filter all MCPS students who are 20yrs and younger in age.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D<-df_Degrees }\OperatorTok{%>%}\StringTok{                    }
\StringTok{         }\KeywordTok{filter}\NormalTok{(HS_classify}\OperatorTok{==}\StringTok{"MCPS"}\NormalTok{)}\OperatorTok{%>%}\StringTok{    }\CommentTok{# filter degrees dataset to obtain students who graduated MCPS highschools}
\StringTok{         }\KeywordTok{filter}\NormalTok{(age}\OperatorTok{==}\StringTok{'18 - 20'} \OperatorTok{|}\StringTok{ }\NormalTok{age }\OperatorTok{==}\StringTok{"< 18"}\NormalTok{) }\CommentTok{# filter students who are 20yrs old and younger. }
\end{Highlighting}
\end{Shaded}

\hypertarget{demographics-of-students-who-graduated-from-mcps-highschools-and-are-20yrs-and-younger.}{%
\section{Demographics of Students who graduated from MCPS highschools
and are 20yrs and
younger.}\label{demographics-of-students-who-graduated-from-mcps-highschools-and-are-20yrs-and-younger.}}

\hypertarget{full-time-versus-part-time-degree-students}{%
\subsection{Full time versus Part-time Degree
Students}\label{full-time-versus-part-time-degree-students}}

Frequency of Students Part time versus Full tim: 2020 vs 2021

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Number of students part time abnd full time  2020 vs 2021}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{df_MCPS20D, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{full_part, }\DataTypeTok{fill=}\NormalTok{full_part)) }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label=}\NormalTok{..count..), }\DataTypeTok{vjust=}\DecValTok{2}\NormalTok{,}\DataTypeTok{size=}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{term_year)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Number of Students Full time versus Part time"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Frequency'}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x=}\KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{strip.background =} \KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{panel.grid =} \KeywordTok{element_blank}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-5-1.pdf}

Proportion of Students Full time versus Part time: 2020 vs 2021

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{group_by}\NormalTok{(term_year) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{count}\NormalTok{(full_part) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{prop =}\NormalTok{ n}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(n)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ full_part, }\DataTypeTok{y =}\NormalTok{ prop)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_col}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill =}\NormalTok{ full_part), }\DataTypeTok{position =} \StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ scales}\OperatorTok{::}\KeywordTok{percent}\NormalTok{(prop), }
                  \DataTypeTok{y =}\NormalTok{ prop, }
                  \DataTypeTok{group =}\NormalTok{ full_part),}
              \DataTypeTok{position =} \KeywordTok{position_dodge}\NormalTok{(}\DataTypeTok{width =} \FloatTok{0.9}\NormalTok{),}
              \DataTypeTok{vjust =} \DecValTok{2}\NormalTok{,}\DataTypeTok{size=}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{term_year)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Proportion of Students Full time versus Part time"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Percentage'}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x=}\KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{strip.background =} \KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{panel.grid =} \KeywordTok{element_blank}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# change in overall MCPS student population from 2020 to 2021}

\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,full_part)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(full_part)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{total_pop =}\KeywordTok{sum}\NormalTok{(n))}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(full_part)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 5
## # Groups:   full_part [2]
##   term_year full_part     n total_pop pct_change
##   <chr>     <chr>     <int>     <int>      <dbl>
## 1 2020      FT         1655      2456      NA   
## 2 2021      FT         1556      2303      -5.98
## 3 2020      PT          801      2456      NA   
## 4 2021      PT          747      2303      -6.74
\end{verbatim}

There was a 5.98\% decrease in full time students who graduated from
MCPS highschools in term year 2021. There was a -6.74\% decrease in part
time students who graduated from MCPS.

\hypertarget{race}{%
\subsection{Race}\label{race}}

Count of Race Groups

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{df_MCPS20D, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{race, }\DataTypeTok{fill=}\NormalTok{race)) }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label=}\NormalTok{..count..), }\DataTypeTok{vjust=}\DecValTok{0}\NormalTok{,}\DataTypeTok{size=}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{term_year }\OperatorTok{+}\StringTok{ }\NormalTok{full_part)}\OperatorTok{+}
\StringTok{      }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x=}\KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{strip.background =} \KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{panel.grid =} \KeywordTok{element_blank}\NormalTok{())}\OperatorTok{+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Number of Students per a Race Group"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Race"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Frequency"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-8-1.pdf}

Full time student: Change in enrollment from 2020 to 2021 based on Race

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate percentage change in full time student enrollment from 2020 to 2021 by  race}

\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,race)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(race)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(race)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 18 x 4
## # Groups:   race [9]
##    term_year race                       n pct_change
##    <chr>     <chr>                  <int>      <dbl>
##  1 2020      Am. Indian / AK Native     5      NA   
##  2 2021      Am. Indian / AK Native     1     -80   
##  3 2020      Asian                    272      NA   
##  4 2021      Asian                    227     -16.5 
##  5 2020      Black / African Am.      389      NA   
##  6 2021      Black / African Am.      326     -16.2 
##  7 2020      Foreign                  103      NA   
##  8 2021      Foreign                   96      -6.80
##  9 2020      Hawaiian / Pac. Isl.       5      NA   
## 10 2021      Hawaiian / Pac. Isl.       3     -40   
## 11 2020      Hispanic                 534      NA   
## 12 2021      Hispanic                 596      11.6 
## 13 2020      Multi-Race                71      NA   
## 14 2021      Multi-Race                63     -11.3 
## 15 2020      Unknown                   11      NA   
## 16 2021      Unknown                    3     -72.7 
## 17 2020      White                    265      NA   
## 18 2021      White                    241      -9.06
\end{verbatim}

Full time students: There was a 16.5\% decline in asian students, 16.1\%
decline in African American students, a 9.1\% decline in white students
and 6.8\% decline in foreign students. Hispanic students increased by
11.6\%.

Part time student: Change in enrollment from 2020 to 2021 based on Race

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate percentage change in full time student enrollment from 2020 to 2021 by  race}

\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,race)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(race)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(race)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 18 x 4
## # Groups:   race [9]
##    term_year race                       n pct_change
##    <chr>     <chr>                  <int>      <dbl>
##  1 2020      Am. Indian / AK Native     4      NA   
##  2 2021      Am. Indian / AK Native     1     -75   
##  3 2020      Asian                     69      NA   
##  4 2021      Asian                     63      -8.70
##  5 2020      Black / African Am.      177      NA   
##  6 2021      Black / African Am.      181       2.26
##  7 2020      Foreign                   73      NA   
##  8 2021      Foreign                   54     -26.0 
##  9 2020      Hawaiian / Pac. Isl.       1      NA   
## 10 2021      Hawaiian / Pac. Isl.       1       0   
## 11 2020      Hispanic                 327      NA   
## 12 2021      Hispanic                 263     -19.6 
## 13 2020      Multi-Race                33      NA   
## 14 2021      Multi-Race                35       6.06
## 15 2020      Unknown                    5      NA   
## 16 2021      Unknown                    2     -60   
## 17 2020      White                    112      NA   
## 18 2021      White                    147      31.2
\end{verbatim}

Part time students: There was an 8.7\% decrease in Asian students, a
26\% decrease in foreign students, 2.3\% increase in african american
students and a 19.6\% decrease in hispanic students. There was a 31.25\%
increase in white students.

\hypertarget{gender}{%
\subsection{Gender}\label{gender}}

Gender of Students

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Gender of students part time and full time  2020 vs 2021}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{df_MCPS20D, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{sex, }\DataTypeTok{fill=}\NormalTok{sex)) }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label=}\NormalTok{..count..), }\DataTypeTok{vjust=}\DecValTok{1}\NormalTok{,}\DataTypeTok{size=}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{term_year}\OperatorTok{+}\NormalTok{full_part)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Gender of Students: Full time versus Part time"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Frequency'}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x=}\KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{strip.background =} \KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{panel.grid =} \KeywordTok{element_blank}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-11-1.pdf}

Calculate percentage change in full time student enrollment from 2020 to
2021 by gender

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate percentage change in full time student enrollment from 2020 to 2021 by  gender}

\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(sex}\OperatorTok{==}\StringTok{"F"}\OperatorTok{|}\NormalTok{sex }\OperatorTok{==}\StringTok{"M"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 4
## # Groups:   sex [2]
##   term_year sex       n pct_change
##   <chr>     <chr> <int>      <dbl>
## 1 2020      F       793      NA   
## 2 2021      F       819       3.28
## 3 2020      M       842      NA   
## 4 2021      M       719     -14.6
\end{verbatim}

Full time students: 14\% decrease in attendance by male students. A
3.27\% decrease in female students.

Calculate percentage change in part time student enrollment from 2020 to
2021 by gender

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate percentage change in part time student enrollment from 2020 to 2021 by  gender}

\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(sex}\OperatorTok{==}\StringTok{"F"}\OperatorTok{|}\NormalTok{sex }\OperatorTok{==}\StringTok{"M"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 4
## # Groups:   sex [2]
##   term_year sex       n pct_change
##   <chr>     <chr> <int>      <dbl>
## 1 2020      F       381      NA   
## 2 2021      F       345      -9.45
## 3 2020      M       401      NA   
## 4 2021      M       395      -1.50
\end{verbatim}

Part time: 9.5\% decrease in female students. 1.5\% decrease in male
students.

Gender and Race breakdown of full time students

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Gender and Race of full time students  2020 vs 2021}

\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{      }\KeywordTok{filter}\NormalTok{(sex }\OperatorTok{%in%}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"F"}\NormalTok{,}\StringTok{"M"}\NormalTok{))}\OperatorTok{%>%}
\StringTok{      }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{      }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{race, }\DataTypeTok{fill=}\NormalTok{race)) }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label=}\NormalTok{..count..), }\DataTypeTok{vjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{size=}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{term_year}\OperatorTok{+}\NormalTok{sex)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Gender and Race of Full time Students"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Frequency'}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x=}\KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{strip.background =} \KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{panel.grid =} \KeywordTok{element_blank}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#    theme(axis.text.x=element_blank(),strip.background = element_blank(),panel.grid = element_blank())}
\end{Highlighting}
\end{Shaded}

Full time Student Enrollment Percentages trend by Gender and race

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate percentage change in student enrollment from 2020 to 2021 by race and gender}

\CommentTok{# create data frames with counts of full time students by race and gender}
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(sex}\OperatorTok{==}\StringTok{"F"}\OperatorTok{|}\NormalTok{sex }\OperatorTok{==}\StringTok{"M"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,race,sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(race,sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 35 x 5
## # Groups:   race, sex [18]
##    term_year race                   sex       n pct_change
##    <chr>     <chr>                  <chr> <int>      <dbl>
##  1 2020      Am. Indian / AK Native F         4      NA   
##  2 2020      Am. Indian / AK Native M         1      NA   
##  3 2021      Am. Indian / AK Native M         1       0   
##  4 2020      Asian                  F       111      NA   
##  5 2021      Asian                  F       115       3.60
##  6 2020      Asian                  M       159      NA   
##  7 2021      Asian                  M       110     -30.8 
##  8 2020      Black / African Am.    F       178      NA   
##  9 2021      Black / African Am.    F       169      -5.06
## 10 2020      Black / African Am.    M       202      NA   
## # ... with 25 more rows
\end{verbatim}

Part time Student Enrollment Percentages trend by Gender and race

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate percentage change in student enrollment from 2020 to 2021 by race and gender}

\CommentTok{# create data frames with counts of full time students by race and gender}
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(sex}\OperatorTok{==}\StringTok{"F"}\OperatorTok{|}\NormalTok{sex }\OperatorTok{==}\StringTok{"M"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,race,sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(race,sex)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 31 x 5
## # Groups:   race, sex [17]
##    term_year race                   sex       n pct_change
##    <chr>     <chr>                  <chr> <int>      <dbl>
##  1 2020      Am. Indian / AK Native M         4      NA   
##  2 2021      Am. Indian / AK Native M         1     -75   
##  3 2020      Asian                  F        30      NA   
##  4 2021      Asian                  F        19     -36.7 
##  5 2020      Asian                  M        37      NA   
##  6 2021      Asian                  M        44      18.9 
##  7 2020      Black / African Am.    F        79      NA   
##  8 2021      Black / African Am.    F        84       6.33
##  9 2020      Black / African Am.    M        96      NA   
## 10 2021      Black / African Am.    M        94      -2.08
## # ... with 21 more rows
\end{verbatim}

\hypertarget{majors}{%
\subsection{Majors}\label{majors}}

Overall Majors trend

Count of Majors in Full time students in 2020

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z1<-}\StringTok{ }\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{      }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"} \OperatorTok{&}\NormalTok{term_year }\OperatorTok{==}\StringTok{"2020"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{       }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{major, }\DataTypeTok{fill=}\NormalTok{major)) }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label=}\NormalTok{..count..), }\DataTypeTok{vjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{size =}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Majors of Full-time Students in 2020  "}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Major"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Frequency"}\NormalTok{)}\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{) }
       
\NormalTok{z1 }\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd
\end{verbatim}

\begin{verbatim}
## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font width unknown for character 0xd
\end{verbatim}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-17-1.pdf}

Count of Majors in Full time students in 2021

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z13<-}\StringTok{ }\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{      }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"} \OperatorTok{&}\NormalTok{term_year }\OperatorTok{==}\StringTok{"2021"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{       }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{major, }\DataTypeTok{fill=}\NormalTok{major)) }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label=}\NormalTok{..count..), }\DataTypeTok{vjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{size =}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Majors of Full-time Students in 2021  "}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Major"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Frequency"}\NormalTok{)}\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{) }
       
\NormalTok{z13 }\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd
\end{verbatim}

\begin{verbatim}
## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font width unknown for character 0xd
\end{verbatim}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-18-1.pdf}

calculate percentage change in full time student majors from 2020 to
2021

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,major)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(major)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(major)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 62 x 4
## # Groups:   major [33]
##    term_year major                        n pct_change
##    <chr>     <chr>                    <int>      <dbl>
##  1 2020      0                            3      NA   
##  2 2021      0                            2     -33.3 
##  3 2020      American Sign Language       5      NA   
##  4 2021      American Sign Language       1     -80   
##  5 2020      Applied Geography            1      NA   
##  6 2021      Applied Geography            2     100   
##  7 2020      Architectural Technology    15      NA   
##  8 2021      Architectural Technology    19      26.7 
##  9 2020      Art                         24      NA   
## 10 2021      Art                         22      -8.33
## # ... with 52 more rows
\end{verbatim}

Count of Majors in Part time students in 2020

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z11<-}\StringTok{ }\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{      }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"} \OperatorTok{&}\NormalTok{term_year }\OperatorTok{==}\StringTok{"2020"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{       }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{major, }\DataTypeTok{fill=}\NormalTok{major)) }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label=}\NormalTok{..count..), }\DataTypeTok{vjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{size =}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Majors of Part-time Students in 2020  "}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Major"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Frequency"}\NormalTok{)}\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{) }
       
\NormalTok{z11 }\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd
\end{verbatim}

\begin{verbatim}
## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font width unknown for character 0xd
\end{verbatim}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-20-1.pdf}
Count of Majors in Part time students in 2021

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z12<-}\StringTok{ }\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{      }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"} \OperatorTok{&}\NormalTok{term_year }\OperatorTok{==}\StringTok{"2021"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{       }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{major, }\DataTypeTok{fill=}\NormalTok{major)) }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}
\StringTok{      }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label=}\NormalTok{..count..), }\DataTypeTok{vjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{size =}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Majors of Part-time Students in 2021  "}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Major"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Frequency"}\NormalTok{)}\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{) }
       
\NormalTok{z12 }\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## width unknown for character 0xd
\end{verbatim}

\begin{verbatim}
## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font width unknown for character 0xd
\end{verbatim}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-21-1.pdf}

calculate percentage change in part time student majors from 2020 to
2021

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,major)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(major)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(major)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 60 x 4
## # Groups:   major [32]
##    term_year major                        n pct_change
##    <chr>     <chr>                    <int>      <dbl>
##  1 2020      0                            5       NA  
##  2 2020      American Sign Language       1       NA  
##  3 2021      American Sign Language       2      100  
##  4 2020      Applied Geography            2       NA  
##  5 2020      Architectural Technology    13       NA  
##  6 2021      Architectural Technology     4      -69.2
##  7 2020      Art                         12       NA  
##  8 2021      Art                         14       16.7
##  9 2020      Broadcast Media              5       NA  
## 10 2021      Broadcast Media              4      -20  
## # ... with 50 more rows
\end{verbatim}

\hypertarget{high-schools}{%
\subsection{High Schools}\label{high-schools}}

\hypertarget{full-time-student}{%
\subsubsection{Full time Student}\label{full-time-student}}

Breakdown of Highschools Full time students in term year 2020 attended
in MCPS

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"} \OperatorTok{&}\StringTok{ }\NormalTok{term_year}\OperatorTok{==}\StringTok{"2020"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{total_pop =}\KeywordTok{sum}\NormalTok{(n))}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_pop=}\NormalTok{ (n}\OperatorTok{/}\NormalTok{total_pop}\OperatorTok{*}\DecValTok{100}\NormalTok{))}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(pct_pop))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 25 x 5
## # Groups:   high_school [25]
##    term_year high_school                        n total_pop pct_pop
##    <chr>     <chr>                          <int>     <int>   <dbl>
##  1 2020      Gaithersburg High School         132      1655    7.98
##  2 2020      Montgomery Blair High School     105      1655    6.34
##  3 2020      Northwest HS - Germantown         92      1655    5.56
##  4 2020      Paint Branch High School          92      1655    5.56
##  5 2020      Springbrook Sr High School        91      1655    5.50
##  6 2020      Wheaton High School               80      1655    4.83
##  7 2020      Clarksburg High School            76      1655    4.59
##  8 2020      Richard Montgomery High School    76      1655    4.59
##  9 2020      Colonel Zadok Magruder HS         75      1655    4.53
## 10 2020      Albert Einstein HS & MC Art Cn    74      1655    4.47
## # ... with 15 more rows
\end{verbatim}

Breakdown of Highschools Full time students in term year 2021 attended
in MCPS

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"} \OperatorTok{&}\StringTok{ }\NormalTok{term_year}\OperatorTok{==}\StringTok{"2021"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{total_pop =}\KeywordTok{sum}\NormalTok{(n))}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_pop=}\NormalTok{ (n}\OperatorTok{/}\NormalTok{total_pop}\OperatorTok{*}\DecValTok{100}\NormalTok{))}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(pct_pop))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 25 x 5
## # Groups:   high_school [25]
##    term_year high_school                        n total_pop pct_pop
##    <chr>     <chr>                          <int>     <int>   <dbl>
##  1 2021      Montgomery Blair High School      97      1556    6.23
##  2 2021      Paint Branch High School          91      1556    5.85
##  3 2021      Wheaton High School               90      1556    5.78
##  4 2021      Gaithersburg High School          89      1556    5.72
##  5 2021      Northwest HS - Germantown         86      1556    5.53
##  6 2021      Colonel Zadok Magruder HS         84      1556    5.40
##  7 2021      Richard Montgomery High School    78      1556    5.01
##  8 2021      Watkins Mill High School          75      1556    4.82
##  9 2021      Clarksburg High School            74      1556    4.76
## 10 2021      James Hubert Blake High School    70      1556    4.50
## # ... with 15 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate percentage change in full time student enrollment from 2020 to 2021 by MCPS highschool}
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(pct_change))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 50 x 4
## # Groups:   high_school [25]
##    term_year high_school                        n pct_change
##    <chr>     <chr>                          <int>      <dbl>
##  1 2021      Rockville High School             65      41.3 
##  2 2021      Wheaton High School               90      12.5 
##  3 2021      Colonel Zadok Magruder HS         84      12   
##  4 2021      Walt Whitman High School          20      11.1 
##  5 2021      Seneca Valley High School         55      10   
##  6 2021      Sherwood High School              68       9.68
##  7 2021      Bethesda Chevy Chase High Schl    43       4.88
##  8 2021      Watkins Mill High School          75       4.17
##  9 2021      Richard Montgomery High School    78       2.63
## 10 2021      Thomas Sprigg Wootton High Sch    33       0   
## # ... with 40 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{v1<-}\StringTok{ }\NormalTok{df_MCPS20D }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{group_by}\NormalTok{(term_year,full_part) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"} \OperatorTok{&}\StringTok{ }\NormalTok{term_year}\OperatorTok{==}\StringTok{"2020"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{    }\KeywordTok{count}\NormalTok{(high_school) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{prop =}\NormalTok{ n}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(n)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ high_school, }\DataTypeTok{y =}\NormalTok{ prop)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_col}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{high_school), }\DataTypeTok{position =} \StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ scales}\OperatorTok{::}\KeywordTok{percent}\NormalTok{(prop,}\FloatTok{0.5}\NormalTok{), }
                  \DataTypeTok{y =}\NormalTok{ prop, }
                  \DataTypeTok{group =}\NormalTok{ high_school),}
              \DataTypeTok{position =} \KeywordTok{position_dodge}\NormalTok{(}\DataTypeTok{width =} \FloatTok{0.9}\NormalTok{),}
              \DataTypeTok{vjust =} \DecValTok{0}\NormalTok{, }\DataTypeTok{size=}\DecValTok{3}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\CommentTok{#  facet_wrap(~term_year )+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"High schools full time students graduated in term year 2020 graduated"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Proportion '}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{, }\DataTypeTok{axis.text.x=}\KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{strip.background =} \KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{panel.grid =} \KeywordTok{element_blank}\NormalTok{()) }
  
\NormalTok{v1}\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{()  }
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-26-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{v1<-}\StringTok{ }\NormalTok{df_MCPS20D }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{group_by}\NormalTok{(term_year,full_part) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"} \OperatorTok{&}\StringTok{ }\NormalTok{term_year}\OperatorTok{==}\StringTok{"2021"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{    }\KeywordTok{count}\NormalTok{(high_school) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{prop =}\NormalTok{ n}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(n)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ high_school, }\DataTypeTok{y =}\NormalTok{ prop)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_col}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{high_school), }\DataTypeTok{position =} \StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ scales}\OperatorTok{::}\KeywordTok{percent}\NormalTok{(prop,}\FloatTok{0.5}\NormalTok{), }
                  \DataTypeTok{y =}\NormalTok{ prop, }
                  \DataTypeTok{group =}\NormalTok{ high_school),}
              \DataTypeTok{position =} \KeywordTok{position_dodge}\NormalTok{(}\DataTypeTok{width =} \FloatTok{0.9}\NormalTok{),}
              \DataTypeTok{vjust =} \DecValTok{0}\NormalTok{, }\DataTypeTok{size=}\DecValTok{3}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\CommentTok{#  facet_wrap(~term_year )+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"High schools full time students graduated in term year 2021 graduated"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Proportion '}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{, }\DataTypeTok{axis.text.x=}\KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{strip.background =} \KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{panel.grid =} \KeywordTok{element_blank}\NormalTok{()) }
  
\NormalTok{v1}\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{()  }
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-27-1.pdf}

\hypertarget{part-time-student}{%
\subsubsection{Part time Student}\label{part-time-student}}

Breakdown of Highschools Part time students in term year 2020 attended
in MCPS

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"} \OperatorTok{&}\StringTok{ }\NormalTok{term_year}\OperatorTok{==}\StringTok{"2020"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{total_pop =}\KeywordTok{sum}\NormalTok{(n))}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_pop=}\NormalTok{ (n}\OperatorTok{/}\NormalTok{total_pop}\OperatorTok{*}\DecValTok{100}\NormalTok{))}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(pct_pop))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 25 x 5
## # Groups:   high_school [25]
##    term_year high_school                        n total_pop pct_pop
##    <chr>     <chr>                          <int>     <int>   <dbl>
##  1 2020      Northwest HS - Germantown         61       801    7.62
##  2 2020      John F. Kennedy High School       56       801    6.99
##  3 2020      Gaithersburg High School          55       801    6.87
##  4 2020      Montgomery Blair High School      54       801    6.74
##  5 2020      Albert Einstein HS & MC Art Cn    44       801    5.49
##  6 2020      Clarksburg High School            43       801    5.37
##  7 2020      Paint Branch High School          41       801    5.12
##  8 2020      Richard Montgomery High School    38       801    4.74
##  9 2020      Watkins Mill High School          38       801    4.74
## 10 2020      Rockville High School             37       801    4.62
## # ... with 15 more rows
\end{verbatim}

Breakdown of Highschools Part time students in term year 2021 attended
in MCPS

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"} \OperatorTok{&}\StringTok{ }\NormalTok{term_year}\OperatorTok{==}\StringTok{"2021"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{total_pop =}\KeywordTok{sum}\NormalTok{(n))}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_pop=}\NormalTok{ (n}\OperatorTok{/}\NormalTok{total_pop}\OperatorTok{*}\DecValTok{100}\NormalTok{))}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(pct_pop))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 25 x 5
## # Groups:   high_school [25]
##    term_year high_school                        n total_pop pct_pop
##    <chr>     <chr>                          <int>     <int>   <dbl>
##  1 2021      Gaithersburg High School          48       747    6.43
##  2 2021      Northwest HS - Germantown         48       747    6.43
##  3 2021      Montgomery Blair High School      39       747    5.22
##  4 2021      Colonel Zadok Magruder HS         38       747    5.09
##  5 2021      Northwood High School             38       747    5.09
##  6 2021      Paint Branch High School          37       747    4.95
##  7 2021      Quince Orchard Sr High School     35       747    4.69
##  8 2021      Walter Johnson High School        35       747    4.69
##  9 2021      Albert Einstein HS & MC Art Cn    34       747    4.55
## 10 2021      Richard Montgomery High School    33       747    4.42
## # ... with 15 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate percentage change in full time student enrollment from 2020 to 2021 by MCPS highschool}
\NormalTok{df_MCPS20D}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year,high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{count}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(term_year)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{group_by}\NormalTok{(high_school)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(term_year,}\DataTypeTok{.by_group=}\OtherTok{TRUE}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change=}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))}\OperatorTok{/}\KeywordTok{lag}\NormalTok{(n)}\OperatorTok{*}\DecValTok{100}\NormalTok{)}\OperatorTok{%>%}
\StringTok{          }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(pct_change))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 50 x 4
## # Groups:   high_school [25]
##    term_year high_school                        n pct_change
##    <chr>     <chr>                          <int>      <dbl>
##  1 2021      Thomas Sprigg Wootton High Sch    24     100   
##  2 2021      Walter Johnson High School        35      75   
##  3 2021      Winston Churchill High School     15      66.7 
##  4 2021      Poolesville Jr-Sr High School     14      55.6 
##  5 2021      Northwood High School             38      52   
##  6 2021      Sherwood High School              30      36.4 
##  7 2021      Walt Whitman High School          14      27.3 
##  8 2021      Colonel Zadok Magruder HS         38      15.2 
##  9 2021      James Hubert Blake High School    30      11.1 
## 10 2021      Damascus High School              19       5.56
## # ... with 40 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{v3<-}\StringTok{ }\NormalTok{df_MCPS20D }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{group_by}\NormalTok{(term_year,full_part) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"} \OperatorTok{&}\StringTok{ }\NormalTok{term_year}\OperatorTok{==}\StringTok{"2020"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{    }\KeywordTok{count}\NormalTok{(high_school) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{prop =}\NormalTok{ n}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(n)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ high_school, }\DataTypeTok{y =}\NormalTok{ prop)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_col}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{high_school), }\DataTypeTok{position =} \StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ scales}\OperatorTok{::}\KeywordTok{percent}\NormalTok{(prop,}\FloatTok{0.5}\NormalTok{), }
                  \DataTypeTok{y =}\NormalTok{ prop, }
                  \DataTypeTok{group =}\NormalTok{ high_school),}
              \DataTypeTok{position =} \KeywordTok{position_dodge}\NormalTok{(}\DataTypeTok{width =} \FloatTok{0.9}\NormalTok{),}
              \DataTypeTok{vjust =} \DecValTok{0}\NormalTok{, }\DataTypeTok{size=}\DecValTok{3}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\CommentTok{#  facet_wrap(~term_year )+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"High schools Part time students graduated in term year 2020 graduated"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Proportion '}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{, }\DataTypeTok{axis.text.x=}\KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{strip.background =} \KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{panel.grid =} \KeywordTok{element_blank}\NormalTok{()) }
  
\NormalTok{v3}\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{()  }
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-31-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{v4<-}\StringTok{ }\NormalTok{df_MCPS20D }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{group_by}\NormalTok{(term_year,full_part) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"} \OperatorTok{&}\StringTok{ }\NormalTok{term_year}\OperatorTok{==}\StringTok{"2021"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{    }\KeywordTok{count}\NormalTok{(high_school) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{prop =}\NormalTok{ n}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(n)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ high_school, }\DataTypeTok{y =}\NormalTok{ prop)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_col}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{high_school), }\DataTypeTok{position =} \StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ scales}\OperatorTok{::}\KeywordTok{percent}\NormalTok{(prop,}\FloatTok{0.5}\NormalTok{), }
                  \DataTypeTok{y =}\NormalTok{ prop, }
                  \DataTypeTok{group =}\NormalTok{ high_school),}
              \DataTypeTok{position =} \KeywordTok{position_dodge}\NormalTok{(}\DataTypeTok{width =} \FloatTok{0.9}\NormalTok{),}
              \DataTypeTok{vjust =} \DecValTok{0}\NormalTok{, }\DataTypeTok{size=}\DecValTok{3}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\CommentTok{#  facet_wrap(~term_year )+}
\StringTok{      }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"High schools Part time students graduated in term year 2021 graduated"}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Proportion '}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\OperatorTok{+}
\StringTok{      }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{, }\DataTypeTok{axis.text.x=}\KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{strip.background =} \KeywordTok{element_blank}\NormalTok{(),}\DataTypeTok{panel.grid =} \KeywordTok{element_blank}\NormalTok{()) }
  
\NormalTok{v4 }\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{()  }
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-32-1.pdf}

\hypertarget{hours-attempted}{%
\section{Hours Attempted}\label{hours-attempted}}

Boxplots of hours\_attempted by year by MCPS students 20yrs and younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p11 =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(df_MCPS20D, }\KeywordTok{aes}\NormalTok{(hours_attempted))}
\NormalTok{p11 }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{full_part)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-33-1.pdf}

Students who register for more than 18 credits require special
permission from the department. Further more a full time student is
classified as someone who is enrolled in 12 or more credits. A part time
student is classified as someone who is enrolled in less than 12
credits. However based on thge dataset, a number of full time students
attempt less than 12 credits and large a number of part time students
attempt more than 12 hours.

Boxplots of hours\_attempted by year by Full time MCPS students 20yrs
and younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{   }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_attempted))}\OperatorTok{+}
\StringTok{   }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-34-1.pdf}

Boxplots of hours\_attempted by year by Part time MCPS students 20yrs
and younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{   }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_attempted))}\OperatorTok{+}
\StringTok{   }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-35-1.pdf}

There are not many outliers in the part time student groups. Term year
2021 seems to have more outliers on the upper end.

Density plot of hours\_attempted by year

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(df_MCPS20D, }\KeywordTok{aes}\NormalTok{(hours_attempted, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{full_part)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Hours attempted"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" Hours Attempted by Full-time Students vs Part-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-36-1.pdf}

Hours attempted by full time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_attempted, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Hours attempted"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" Hours Attempted by Full-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-37-1.pdf}

Fivenum Summary of Full time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(race,term_year)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{n =} \KeywordTok{n}\NormalTok{(),}
            \DataTypeTok{min =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{1}\NormalTok{],}
            \DataTypeTok{Q1 =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{2}\NormalTok{],}
            \DataTypeTok{median =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{3}\NormalTok{],}
            \DataTypeTok{Q3 =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{4}\NormalTok{],}
            \DataTypeTok{max =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{5}\NormalTok{],}
            \DataTypeTok{mean=} \KeywordTok{mean}\NormalTok{(hours_attempted),}
            \DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(hours_attempted))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'race'. You can override using the `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 18 x 10
## # Groups:   race [9]
##    race               term_year     n   min    Q1 median    Q3   max  mean    sd
##    <chr>              <chr>     <int> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>
##  1 Am. Indian / AK N~ 2020          5     6  13       17  19      36  18.2 11.1 
##  2 Am. Indian / AK N~ 2021          1    13  13       13  13      13  13   NA   
##  3 Asian              2020        272     6  13       15  20      52  17.7  8.13
##  4 Asian              2021        227     7  13       15  17      46  16.8  7.00
##  5 Black / African A~ 2020        389     5  12       13  14      42  13.7  3.53
##  6 Black / African A~ 2021        326     4  12       14  16      38  14.9  4.31
##  7 Foreign            2020        103     7  12       14  17      31  14.8  4.26
##  8 Foreign            2021         96     7  12.5     15  16      37  15.7  5.29
##  9 Hawaiian / Pac. I~ 2020          5     9  12       13  13      15  12.4  2.19
## 10 Hawaiian / Pac. I~ 2021          3    12  15.5     19  24.5    30  20.3  9.07
## 11 Hispanic           2020        534     4  12       13  15      39  14.2  4.43
## 12 Hispanic           2021        596     3  12       14  16      43  15.0  4.33
## 13 Multi-Race         2020         71     6  12       13  17      44  16.7  8.04
## 14 Multi-Race         2021         63     6  12       14  16.5    43  15.7  6.22
## 15 Unknown            2020         11     9  12       14  15      31  15    5.78
## 16 Unknown            2021          3    12  12       12  13      14  12.7  1.15
## 17 White              2020        265     8  12       13  16      46  15.9  7.08
## 18 White              2021        241     7  13       14  17      54  16.5  6.37
\end{verbatim}

Hours attempted by part time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_attempted, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Hours attempted"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" Hours Attempted by Part-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-39-1.pdf}

Fivenum Summary of Part time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(race,term_year)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{n =} \KeywordTok{n}\NormalTok{(),}
            \DataTypeTok{min =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{1}\NormalTok{],}
            \DataTypeTok{Q1 =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{2}\NormalTok{],}
            \DataTypeTok{median =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{3}\NormalTok{],}
            \DataTypeTok{Q3 =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{4}\NormalTok{],}
            \DataTypeTok{max =} \KeywordTok{fivenum}\NormalTok{(hours_attempted)[}\DecValTok{5}\NormalTok{],}
            \DataTypeTok{mean=} \KeywordTok{mean}\NormalTok{(hours_attempted),}
            \DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(hours_attempted))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'race'. You can override using the `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 18 x 10
## # Groups:   race [9]
##    race               term_year     n   min    Q1 median    Q3   max  mean    sd
##    <chr>              <chr>     <int> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>
##  1 Am. Indian / AK N~ 2020          4     3   3      5.5   8.5     9  5.75  3.20
##  2 Am. Indian / AK N~ 2021          1     6   6      6     6       6  6    NA   
##  3 Asian              2020         69     2   6      9    10      33  8.62  4.94
##  4 Asian              2021         63     3   7.5    9    11      21  8.90  3.64
##  5 Black / African A~ 2020        177     1   6      7     9      15  7.28  2.62
##  6 Black / African A~ 2021        181     1   6      8    10      25  7.80  3.37
##  7 Foreign            2020         73     3   6      8    10      23  8.18  3.89
##  8 Foreign            2021         54     3   5      9    10      29  8.61  4.38
##  9 Hawaiian / Pac. I~ 2020          1     6   6      6     6       6  6    NA   
## 10 Hawaiian / Pac. I~ 2021          1     5   5      5     5       5  5    NA   
## 11 Hispanic           2020        327     1   6      8     9      21  7.84  3.06
## 12 Hispanic           2021        263     1   6      8    11      42  8.73  4.41
## 13 Multi-Race         2020         33     1   4      8     9      12  7.03  2.98
## 14 Multi-Race         2021         35     3   6      9    10      26  8.34  3.90
## 15 Unknown            2020          5     7   9     10    10      10  9.2   1.30
## 16 Unknown            2021          2     4   4      6.5   9       9  6.5   3.54
## 17 White              2020        112     1   6      8    10      33  8.15  4.47
## 18 White              2021        147     3   5      8    10      39  8.43  5.02
\end{verbatim}

\hypertarget{hours-earned}{%
\section{Hours Earned}\label{hours-earned}}

Boxplots of Hours Earned by year by MCPS students 20yrs and younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p11 =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(df_MCPS20D, }\KeywordTok{aes}\NormalTok{(hours_earned))}
\NormalTok{p11 }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{full_part)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-41-1.pdf}

Boxplots of hours\_earned by year by Full time MCPS students 20yrs and
younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{   }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_earned))}\OperatorTok{+}
\StringTok{   }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-42-1.pdf}

Boxplots of hours\_earned by year by Part time MCPS students 20yrs and
younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{   }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_earned))}\OperatorTok{+}
\StringTok{   }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-43-1.pdf}

There are not many outliers in the part time student groups. Term year
2021 seems to have more outliers on the upper end.

Density plot of hours\_earned by year

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(df_MCPS20D, }\KeywordTok{aes}\NormalTok{(hours_earned, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{full_part)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Hours Earned"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" Hours Earned by Full-time vs Part-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-44-1.pdf}

Hours\_earned by full time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_earned, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Hours Earned"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" Hours Earned by Full-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-45-1.pdf}

Fivenum Summary of Full time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(race,term_year)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{n =} \KeywordTok{n}\NormalTok{(),}
            \DataTypeTok{min =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{1}\NormalTok{],}
            \DataTypeTok{Q1 =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{2}\NormalTok{],}
            \DataTypeTok{median =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{3}\NormalTok{],}
            \DataTypeTok{Q3 =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{4}\NormalTok{],}
            \DataTypeTok{max =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{5}\NormalTok{],}
            \DataTypeTok{mean=} \KeywordTok{mean}\NormalTok{(hours_earned),}
            \DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(hours_earned))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'race'. You can override using the `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 18 x 10
## # Groups:   race [9]
##    race               term_year     n   min    Q1 median    Q3   max  mean    sd
##    <chr>              <chr>     <int> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>
##  1 Am. Indian / AK N~ 2020          5     0  10       14  19      36 15.8  13.3 
##  2 Am. Indian / AK N~ 2021          1    13  13       13  13      13 13    NA   
##  3 Asian              2020        272     0   9       13  17      52 14.7   9.15
##  4 Asian              2021        227     0   9       12  16      46 13.4   8.53
##  5 Black / African A~ 2020        389     0   6        9  12      42  8.85  5.58
##  6 Black / African A~ 2021        326     0   6        9  13      37  9.55  6.53
##  7 Foreign            2020        103     0   6        9  13      31 10.4   6.44
##  8 Foreign            2021         96     0   6       10  13      37 10.6   7.56
##  9 Hawaiian / Pac. I~ 2020          5     0   0        9  12      13  6.8   6.38
## 10 Hawaiian / Pac. I~ 2021          3     9  12.5     16  23      30 18.3  10.7 
## 11 Hispanic           2020        534     0   6        9  12      38  9.57  6.50
## 12 Hispanic           2021        596     0   6       10  13      33  9.73  6.36
## 13 Multi-Race         2020         71     0   7       12  15      44 13.4   9.76
## 14 Multi-Race         2021         63     0   6       10  13.5    43 10.8   8.69
## 15 Unknown            2020         11     3   5        9  13      31 10.5   7.90
## 16 Unknown            2021          3     3   5        7   9.5    12  7.33  4.51
## 17 White              2020        265     0   7       11  15      46 12.3   8.88
## 18 White              2021        241     0   7       12  15      54 12.5   8.22
\end{verbatim}

hours\_earned by part time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_earned, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Hours Earned"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" Hours Earned by Part-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-47-1.pdf}

Fivenum Summary of Part time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(race,term_year)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{n =} \KeywordTok{n}\NormalTok{(),}
            \DataTypeTok{min =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{1}\NormalTok{],}
            \DataTypeTok{Q1 =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{2}\NormalTok{],}
            \DataTypeTok{median =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{3}\NormalTok{],}
            \DataTypeTok{Q3 =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{4}\NormalTok{],}
            \DataTypeTok{max =} \KeywordTok{fivenum}\NormalTok{(hours_earned)[}\DecValTok{5}\NormalTok{],}
            \DataTypeTok{mean=} \KeywordTok{mean}\NormalTok{(hours_earned),}
            \DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(hours_earned))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'race'. You can override using the `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 18 x 10
## # Groups:   race [9]
##    race              term_year     n   min    Q1 median    Q3   max  mean     sd
##    <chr>             <chr>     <int> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl>  <dbl>
##  1 Am. Indian / AK ~ 2020          4     0   1.5    3       3     3  2.25  1.5  
##  2 Am. Indian / AK ~ 2021          1     3   3      3       3     3  3    NA    
##  3 Asian             2020         69     0   0      4       6    33  4.81  5.50 
##  4 Asian             2021         63     0   3      3       6    21  4.73  4.48 
##  5 Black / African ~ 2020        177     0   0      3       4    11  2.73  2.82 
##  6 Black / African ~ 2021        181     0   0      1       6    22  2.81  3.72 
##  7 Foreign           2020         73     0   0      3       6    21  3.96  4.60 
##  8 Foreign           2021         54     0   0      0       6    29  3.09  5.04 
##  9 Hawaiian / Pac. ~ 2020          1     0   0      0       0     0  0    NA    
## 10 Hawaiian / Pac. ~ 2021          1     3   3      3       3     3  3    NA    
## 11 Hispanic          2020        327     0   0      3       6    21  3.48  3.84 
## 12 Hispanic          2021        263     0   0      3       6    42  4.65  5.14 
## 13 Multi-Race        2020         33     0   1      3       9    11  4.27  3.83 
## 14 Multi-Race        2021         35     0   0      3       6    26  4.11  4.95 
## 15 Unknown           2020          5     0   1      1       4     9  3     3.67 
## 16 Unknown           2021          2     3   3      3.5     4     4  3.5   0.707
## 17 White             2020        112     0   0      4       7    27  4.74  4.87 
## 18 White             2021        147     0   3      4       7    33  5.16  5.14
\end{verbatim}

\hypertarget{gpa}{%
\section{GPA}\label{gpa}}

Boxplots of GPA by year by MCPS students 20yrs and younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p11 =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(df_MCPS20D, }\KeywordTok{aes}\NormalTok{(mc_gpa))}
\NormalTok{p11 }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{full_part)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-49-1.pdf}

Boxplots of GPA by year by Full time MCPS students 20yrs and younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{   }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(mc_gpa))}\OperatorTok{+}
\StringTok{   }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-50-1.pdf}

Boxplots of GPA by year by Part time MCPS students 20yrs and younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{   }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(mc_gpa))}\OperatorTok{+}
\StringTok{   }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-51-1.pdf}

Density plot of GPA by year

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(df_MCPS20D, }\KeywordTok{aes}\NormalTok{(mc_gpa, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{full_part)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"GPA"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" GPA by Full-time vs Part-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-52-1.pdf}

GPA by full time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(mc_gpa, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"GPA"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" GPA of Full-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-53-1.pdf}

Fivenum Summary of Full time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(race,term_year)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{n =} \KeywordTok{n}\NormalTok{(),}
            \DataTypeTok{min =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{1}\NormalTok{],}
            \DataTypeTok{Q1 =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{2}\NormalTok{],}
            \DataTypeTok{median =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{3}\NormalTok{],}
            \DataTypeTok{Q3 =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{4}\NormalTok{],}
            \DataTypeTok{max =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{5}\NormalTok{],}
            \DataTypeTok{mean=} \KeywordTok{mean}\NormalTok{(mc_gpa),}
            \DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(mc_gpa))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'race'. You can override using the `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 18 x 10
## # Groups:   race [9]
##    race              term_year     n   min    Q1 median    Q3   max  mean     sd
##    <chr>             <chr>     <int> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl>  <dbl>
##  1 Am. Indian / AK ~ 2020          5  0     2.35   2.9   3.5   4     2.55  1.55 
##  2 Am. Indian / AK ~ 2021          1  2.77  2.77   2.77  2.77  2.77  2.77 NA    
##  3 Asian             2020        272  0     2.33   3.3   3.73  4     2.93  1.03 
##  4 Asian             2021        227  0     2.5    3.23  3.71  4     2.88  1.12 
##  5 Black / African ~ 2020        389  0     1.5    2.5   3.14  4     2.25  1.18 
##  6 Black / African ~ 2021        326  0     1.33   2.67  3.4   4     2.31  1.30 
##  7 Foreign           2020        103  0     2      3     3.65  4     2.71  1.20 
##  8 Foreign           2021         96  0     1.46   2.82  3.69  4     2.48  1.35 
##  9 Hawaiian / Pac. ~ 2020          5  0     0      2.25  2.67  3.77  1.74  1.68 
## 10 Hawaiian / Pac. ~ 2021          3  1.75  2.22   2.68  3.34  4     2.81  1.13 
## 11 Hispanic          2020        534  0     1.5    2.70  3.44  4     2.38  1.25 
## 12 Hispanic          2021        596  0     1.23   2.66  3.33  4     2.29  1.30 
## 13 Multi-Race        2020         71  0     2      2.75  3.5   4     2.59  1.13 
## 14 Multi-Race        2021         63  0     1.5    2.6   3.54  4     2.37  1.35 
## 15 Unknown           2020         11  0.33  2.12   2.33  3.32  4     2.55  1.00 
## 16 Unknown           2021          3  2.55  2.65   2.75  3.38  4     3.1   0.786
## 17 White             2020        265  0     1.8    3     3.6   4     2.59  1.22 
## 18 White             2021        241  0     2      3     3.69  4     2.67  1.26
\end{verbatim}

GPA of Part time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(mc_gpa, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Hours Earned"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" GPA of Part-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-55-1.pdf}

Fivenum Summary of Part time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(race,term_year)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{n =} \KeywordTok{n}\NormalTok{(),}
            \DataTypeTok{min =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{1}\NormalTok{],}
            \DataTypeTok{Q1 =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{2}\NormalTok{],}
            \DataTypeTok{median =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{3}\NormalTok{],}
            \DataTypeTok{Q3 =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{4}\NormalTok{],}
            \DataTypeTok{max =} \KeywordTok{fivenum}\NormalTok{(mc_gpa)[}\DecValTok{5}\NormalTok{],}
            \DataTypeTok{mean=} \KeywordTok{mean}\NormalTok{(mc_gpa),}
            \DataTypeTok{sd =} \KeywordTok{sd}\NormalTok{(mc_gpa))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'race'. You can override using the `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 18 x 10
## # Groups:   race [9]
##    race              term_year     n   min    Q1 median    Q3   max  mean     sd
##    <chr>             <chr>     <int> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl>  <dbl>
##  1 Am. Indian / AK ~ 2020          4     0  0.5    1.25  2.25     3  1.38  1.25 
##  2 Am. Indian / AK ~ 2021          1     2  2      2     2        2  2    NA    
##  3 Asian             2020         69     0  0      2.3   3.33     4  2.01  1.54 
##  4 Asian             2021         63     0  0.8    2     3.28     4  1.94  1.48 
##  5 Black / African ~ 2020        177     0  0      1.33  2.71     4  1.46  1.38 
##  6 Black / African ~ 2021        181     0  0      0.33  2.33     4  1.13  1.32 
##  7 Foreign           2020         73     0  0      2     3        4  1.65  1.51 
##  8 Foreign           2021         54     0  0      0     2.67     4  1.20  1.46 
##  9 Hawaiian / Pac. ~ 2020          1     0  0      0     0        0  0    NA    
## 10 Hawaiian / Pac. ~ 2021          1     4  4      4     4        4  4    NA    
## 11 Hispanic          2020        327     0  0      1.5   3        4  1.60  1.50 
## 12 Hispanic          2021        263     0  0      2     3        4  1.73  1.43 
## 13 Multi-Race        2020         33     0  0.67   2     3.5      4  1.99  1.51 
## 14 Multi-Race        2021         35     0  0      2.5   3        4  1.80  1.55 
## 15 Unknown           2020          5     0  0.75   2     3.67     4  2.08  1.75 
## 16 Unknown           2021          2     3  3      3.5   4        4  3.5   0.707
## 17 White             2020        112     0  0      2     3.33     4  1.86  1.54 
## 18 White             2021        147     0  0.55   2.5   3.33     4  2.16  1.49
\end{verbatim}

\# Hours Earned Rate

Density plot of Hours Earned Rate by year

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(df_MCPS20D, }\KeywordTok{aes}\NormalTok{(hours_earned_rate, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{full_part)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Hours Earned Rate"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlim}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-57-1.pdf}

Boxplots of Hours Earned Rate of Full time MCPS students 20yrs and
younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{   }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_earned_rate))}\OperatorTok{+}
\StringTok{   }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-58-1.pdf}

Boxplots of Hours Earned Rate of Part time MCPS students 20yrs and
younger

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{   }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_earned_rate))}\OperatorTok{+}
\StringTok{   }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{colour =}\NormalTok{ term_year)) }\OperatorTok{+}
\StringTok{       }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-59-1.pdf}

Hours Earned Rate of full time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_earned_rate, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"GPA"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" Hours Earned Rate of Full-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-60-1.pdf}

Hours Earned Rate of part time students

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(race}\OperatorTok{==}\StringTok{"White"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Asian"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Hispanic"} \OperatorTok{|}\NormalTok{race}\OperatorTok{==}\StringTok{"Black / African Am."}\NormalTok{ )}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(., }\KeywordTok{aes}\NormalTok{(hours_earned_rate, }\DataTypeTok{fill =}\NormalTok{ term_year)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{race)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"GPA"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{( }\StringTok{"Density"}\NormalTok{)}\OperatorTok{+}
\StringTok{   }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{" Hours Earned Rate of Part-time Students"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-61-1.pdf}

\hypertarget{distribution-of-variables-and-correlation}{%
\section{Distribution of Variables and
Correlation}\label{distribution-of-variables-and-correlation}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(GGally)}
\CommentTok{# plot distributions and correlation of variables}
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(term_year}\OperatorTok{==}\StringTok{"2020"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{              }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{              }\KeywordTok{ggpairs}\NormalTok{(., }\DataTypeTok{columns =} \KeywordTok{c}\NormalTok{(}\StringTok{"hours_attempted"}\NormalTok{,}\StringTok{"hours_earned"}\NormalTok{, }\StringTok{"mc_gpa"}\NormalTok{,}\StringTok{"hours_earned_rate"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-62-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(GGally)}
\CommentTok{# plot distributions and correlation of variables}
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(term_year}\OperatorTok{==}\StringTok{"2021"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{              }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"FT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{              }\KeywordTok{ggpairs}\NormalTok{(., }\DataTypeTok{columns =} \KeywordTok{c}\NormalTok{(}\StringTok{"hours_attempted"}\NormalTok{,}\StringTok{"hours_earned"}\NormalTok{, }\StringTok{"mc_gpa"}\NormalTok{,}\StringTok{"hours_earned_rate"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-63-1.pdf}

\hypertarget{distribution-of-variables-and-correlation-1}{%
\subsection{Distribution of Variables and
Correlation}\label{distribution-of-variables-and-correlation-1}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(GGally)}
\CommentTok{# plot distributions and correlation of variables}
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(term_year}\OperatorTok{==}\StringTok{"2020"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{              }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{              }\KeywordTok{ggpairs}\NormalTok{(., }\DataTypeTok{columns =} \KeywordTok{c}\NormalTok{(}\StringTok{"hours_attempted"}\NormalTok{,}\StringTok{"hours_earned"}\NormalTok{, }\StringTok{"mc_gpa"}\NormalTok{,}\StringTok{"hours_earned_rate"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-64-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(GGally)}
\CommentTok{# plot distributions and correlation of variables}
\NormalTok{df_MCPS20D}\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(term_year}\OperatorTok{==}\StringTok{"2021"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{              }\KeywordTok{filter}\NormalTok{(full_part}\OperatorTok{==}\StringTok{"PT"}\NormalTok{)}\OperatorTok{%>%}
\StringTok{              }\KeywordTok{ggpairs}\NormalTok{(., }\DataTypeTok{columns =} \KeywordTok{c}\NormalTok{(}\StringTok{"hours_attempted"}\NormalTok{,}\StringTok{"hours_earned"}\NormalTok{, }\StringTok{"mc_gpa"}\NormalTok{,}\StringTok{"hours_earned_rate"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{MCPS_students_files/figure-latex/unnamed-chunk-65-1.pdf}

\end{document}
